### ISSUE TITLE
Open a Gitter/Slack/Discord channel?

### ISSUE THREAD

**Issue by excalliburbd** [riyadhalnur/mongoose-algolia-index#6]
Hi,
I would like to contribute to this project. Frankly I don't know very much MongoDB and didn't know what Algolia was before this. But I love how everything is documented here and think this would be a great learning opportunity. Would you consider creating a place where we can discuss newbie stuff not worth a new issue? 

Thanks

**Comment by riyadhalnur** [comment]
Hi,

Thank you for the love and support. 😃  It's awesome that you want to contribute to this project. I can use all the help I can get. I think it would be great to create a chat channel for this. I'll open one soon! 🎉
